Сделал класс Application singleton, чтобы не перекидывать объект клас…
EgorkA82/RTetris pull request #14
Opened 2024-04-27 12:59 UTC by ifef228

…са между методами Menu и Settings

2024-04-30 12:46 UTC, EgorkA82 commented on src/Screen/Settings.cpp
> +//Можно сделать класс Button шаблонным.
В лямбду в нашем случае действительно нельзя передавать каких-либо параметров, потому что наша кнопка просто запускает каллбек, иначе будет сложно и запутанно.

Мы можем при объявлении лямбды указать, какие переменные и ссылки включить в область видимости лямбды. Тогда мы сможем с ними работать при вызове функции, хоть мы их и не передавали в функцию как аргументы

2024-04-30 12:46 UTC, EgorkA82 commented on src/Screen/Settings.cpp
> +}
CppCheck у меня тоже ни на что не ругается, но GCC ругается, что здесь незадействованы `target` и `states`

2024-05-04 12:24 UTC, EgorkA82 requested changes
Провел ревью текущего варианта ветки

2024-05-04 12:24 UTC, EgorkA82 commented on include/Screen/Settings.h
> +#include "BaseScreen.h"
Ставь, пожалуйста, пустую строчку между, это разные блоки кода для разных целей

2024-05-04 12:24 UTC, EgorkA82 commented on src/Application.cpp
> +void Application::setCurrentScreen(BaseScreen* newScreen)
В этот метод напрашивается смена `bool isActive`. Иначе нам самим придется следить за переключением состояний, что не есть хорошо.

В начале функции мы отключаем активность текущего окна, а после ресета ставим новому экрану активность. Тогда в скринах нам не нужны отдельные поля и геттеры/сеттеры, только в базовом классе

2024-05-04 12:24 UTC, EgorkA82 commented on src/Screen/Settings.cpp
> +        if(settingsActive){//чтобы кнопки перестали обрабатываться, если меню настроек не является текущим экраном
В такой проверке нет смысла, ведь Application и так передает события только в свой текущий экран. В остальные экраны ивенты не отправляются

2024-05-04 13:01 UTC, ifef228 commented on src/Screen/Settings.cpp
> +        if(settingsActive){//чтобы кнопки перестали обрабатываться, если меню настроек не является текущим экраном
я эту проверку добавил, потому что без нее вылазит segmentation fault.
При отработки колбека одной из кнопок меняется экран, но этот цикл доходит до конца, из за чего начинают обрабатываться события уже удаленной кнопки

2024-05-04 13:03 UTC, ifef228 commented on src/Application.cpp
> +void Application::setCurrentScreen(BaseScreen* newScreen)
я подумаю над этим

2024-05-04 19:34 UTC, EgorkA82 commented on src/Screen/Settings.cpp
> +        if(settingsActive){//чтобы кнопки перестали обрабатываться, если меню настроек не является текущим экраном
Тогда надо не проверять активность при каждой итерации, а сразу брейкать цикл, чтобы лишних циклов не гонять

2024-05-19 06:32 UTC, merged